### ISSUE TITLE
mdnsd busyloop

### ISSUE THREAD

**Issue by fingon** [sbyx/ohybridproxy#2]
23:11:02.388508 gettimeofday({1442005862, 389747}, NULL) = 0
23:11:02.390098 gettimeofday({1442005862, 390595}, NULL) = 0
23:11:02.390886 gettimeofday({1442005862, 391374}, NULL) = 0
23:11:02.391678 _newselect(1096, [3 4 6 9 1025 1027 1028 1029 1030 1031 1032 1033 1034 1039 1041 1042 1043 1056 1060 1061 1067 1068 1070 1071 1072 1073 1088 1089 1090 1094], NULL, NULL, {952314, 251953}) = -1 EBADF (Bad file descriptor)
23:11:02.393239 rt_sigprocmask(SIG_BLOCK, [HUP INT PIPE TERM USR1], NULL, 16) = 0
23:11:02.394087 rt_sigprocmask(SIG_UNBLOCK, [HUP INT PIPE TERM USR1], NULL, 16) = 0
23:11:02.394899 gettimeofday({1442005862, 395385}, NULL) = 0
23:11:02.395667 gettimeofday({1442005862, 396154}, NULL) = 0
23:11:02.396456 gettimeofday({1442005862, 396940}, NULL) = 0
23:11:02.397220 gettimeofday({1442005862, 397804}, NULL) = 0
23:11:02.398129 gettimeofday({1442005862, 398740}, NULL) = 0
23:11:02.399077 _newselect(1096, [3 4 6 9 1025 1027 1028 1029 1030 1031 1032 1033 1034 1039 1041 1042 1043 1058 1059 1061 1063 1064 1067 1068 1069 1071 1072 1073 1088 1089 1090 1094], NULL, NULL, {952314, 244140}) = -1 EBADF (Bad file descriptor)
23:11:02.401086 rt_sigprocmask(SIG_BLOCK, [HUP INT PIPE TERM USR1], NULL, 16) = 0

thoughts: do we have too many FDs? (=ratelimit mdnsresponder requests?)

is there mdnsresponder bug?

**Comment by toreanderson** [comment]
I'd like to add that when this bug occurs, it is quite disruptive. Not only because it monopolises the poor CPU on the routers, but also because hostname lookups for domains under the `.home` domain starts timing out. For some reason, several of the applications I use regularly have a habit of look up their own hostname in DNS with the resolver search path added, and for some reason they are doing so in a blocking fashion. So the UI of the application tends to freeze completely. Killing mdnsd (which then gets automatically restarted) alleviates the problem.

**Comment by fingon** [comment]
Not ohybridproxy issue; closing, fixed in trunk OpenWrt packages feed mdnsresponder package (and maybe backported to 15.05, but I doubt a binary package exists yet).
